### ISSUE TITLE
Не информативное название

### ISSUE THREAD

**Issue by giffell** [votafore/MVP#3]
https://github.com/votafore/MVP/blob/64c5e6f2a9829bfe6f606b42989e411218ed1970/app/src/main/java/com/votafore/mvp/ActivityMain.java#L29

**Comment by giffell** [comment]
Для mLoadManager тоже самое, не надо никаких букв `m`

**Comment by votafore** [comment]
https://github.com/votafore/MVP/commit/2c21470771baa5bfb6f35d108fe10025c60ed3bb
