### ISSUE TITLE
А что запрещает сразу при объявлении переменной создать новый?

### ISSUE THREAD

**Issue by giffell** [votafore/MVP#6]
https://github.com/votafore/MVP/blob/64c5e6f2a9829bfe6f606b42989e411218ed1970/app/src/main/java/com/votafore/mvp/utils/RVAdapter.java#L44

**Comment by votafore** [comment]
https://github.com/votafore/MVP/commit/2c21470771baa5bfb6f35d108fe10025c60ed3bb
