### ISSUE TITLE
Зачем это нужно?

### ISSUE THREAD

**Issue by giffell** [votafore/MVP#7]
https://github.com/votafore/MVP/blob/64c5e6f2a9829bfe6f606b42989e411218ed1970/app/src/main/java/com/votafore/mvp/models/Loader.java#L12

**Comment by votafore** [comment]
Собственно это остаток от прошлой версии класса. Надо было удалить.

**Comment by votafore** [comment]
https://github.com/votafore/MVP/commit/2c21470771baa5bfb6f35d108fe10025c60ed3bb
